spring:
  config:
    import: vault://secret/payment-service
  cloud:
    vault:
      host: vault
      port: 8200
      scheme: http
      token: root
      kv:
        enabled: true
  application:
    name: payment-service
